baseURL            = "https://kyuko4437.github.io/"
languageCode       = "ja"
title              = "魔女の脳 公式サイト"
theme              = "PaperMod"
canonifyURLs       = true          # すべて絶対パス
disableLiveReload  = true          # PaperMod 側では無視されるが残してOK

[params]
  env = "production"               # ★ livereload.js を完全に無効化

[build]
  disableFingerprinting = ["css", "js"]  # SRI / ハッシュを付けない

[[menu.main]]
  identifier = "blog"
  name       = "ブログ"
  url        = "/blog/"
  weight     = 1

[[menu.main]]
  identifier = "games"
  name       = "ゲーム"
  url        = "/games/"
  weight     = 2

[[menu.main]]
  identifier = "art"
  name       = "イラスト"
  url        = "/art/"
  weight     = 3

[[menu.main]]
  identifier = "contact"
  name       = "連絡"
  url        = "/contact/"
  weight     = 4
